### ISSUE TITLE
Broken link to Kerberos setup

### ISSUE THREAD

**Issue by skontar** [RedHatProductSecurity/osidb#10]
[Kerberos setup](https://github.com/RedHatProductSecurity/osidb/blob/master/docs/user/TUTORIAL.md) contains following:

> Please refer to our [README](https://github.com/RedHatProductSecurity/osidb/blob/master/docs/user/AUTH.md#kerberos-authentication), you may not be able to authenticate if you don't follow the instructions laid in the linked document.

The target does not exist.

**Comment by osoukup** [comment]
Good catch! This should refer to https://github.com/RedHatProductSecurity/osidb/tree/master/krb5_auth and the broken link is probably a result of some moving around.
