### ISSUE TITLE
Minor typos in TUTORIAL.md

### ISSUE THREAD

**Issue by pedrohc** [RedHatProductSecurity/osidb#837]
I think both lines bellow should be using POST requests and not GET, the same way as their curl counterpart.

https://github.com/RedHatProductSecurity/osidb/blob/f340f1a7fe8c084f276ee4a6ea912f78ec497962/docs/user/TUTORIAL.md?plain=1#L133

https://github.com/RedHatProductSecurity/osidb/blob/f340f1a7fe8c084f276ee4a6ea912f78ec497962/docs/user/TUTORIAL.md?plain=1#L166

**Comment by jobselko** [comment]
Solved in #841
